### ISSUE TITLE
not installing in mac 

### ISSUE THREAD

**Issue by Banginpadr** [instagrambot/Instagram-scraper-with-autopost#3]
RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************
    
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-sviwmcb1/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-record-sa49fl5_/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-sviwmcb1/dlib/

i have cmake on my pc but for some reason im getting this error any ideas how to fix this? when i run pip -r install req... i get this error. thank you.

**Comment by reliefs** [comment]
Sorry, I can't locate. Do you have more error logs ?

**Comment by Banginpadr** [comment]
> Sorry, I can't locate the error. Do you have more error logs ?

pip install -r requirements.txt
Requirement already satisfied: instabot in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.30.0)
Requirement already satisfied: instagram-scraper in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (1.6.0)
Collecting face_recognition (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/3f/ed/ad9a28042f373d4633fc8b49109b623597d6f193d3bbbef7780a5ee8eef2/face_recognition-1.2.3-py2.py3-none-any.whl
Requirement already satisfied: tqdm>=4.30.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (4.31.1)
Requirement already satisfied: requests>=2.21.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (2.21.0)
Requirement already satisfied: requests-toolbelt>=0.8.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (0.9.1)
Requirement already satisfied: itsdangerous>=0.24 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: click>=5.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied: schedule>=0.6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: pysocks>=1.6.8 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (1.6.8)
Requirement already satisfied: responses>=0.10.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (0.10.6)
Requirement already satisfied: future>=0.17.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (0.17.1)
Requirement already satisfied: six>=1.12.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (1.12.0)
Requirement already satisfied: huepy>=0.9.8.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from instabot->-r requirements.txt (line 1)) (0.9.8.1)
Collecting numpy (from face_recognition->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/a6/6f/cb20ccd8f0f8581e0e090775c0e3c3e335b037818416e6fa945d924397d2/numpy-1.16.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting face-recognition-models>=0.3.0 (from face_recognition->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/cf/3b/4fd8c534f6c0d1b80ce0973d01331525538045084c73c153ee6df20224cf/face_recognition_models-0.3.0.tar.gz
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from face_recognition->-r requirements.txt (line 3)) (5.2.0)
Collecting dlib>=19.7 (from face_recognition->-r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.21.0->instabot->-r requirements.txt (line 1)) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.21.0->instabot->-r requirements.txt (line 1)) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.21.0->instabot->-r requirements.txt (line 1)) (2.7)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from requests>=2.21.0->instabot->-r requirements.txt (line 1)) (1.24.1)
Installing collected packages: numpy, face-recognition-models, dlib, face-recognition
  Running setup.py install for face-recognition-models ... done
  Running setup.py install for dlib ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-record-t6ffto4i/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    package init file 'dlib/__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/setup.py", line 261, in <module>
        'Topic :: Software Development',
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/setup.py", line 125, in get_cmake_version
        "\n*******************************************************************\n")
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************
    
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-record-t6ffto4i/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/r3/2y0xmpzd46vbw33g_jm0dxxc0000gn/T/pip-install-2ivm14ir/dlib/

**Comment by reliefs** [comment]
Try to do this command 
brew install dlib and then run pip install again.
Did it work?

**Comment by Banginpadr** [comment]
> Try to do this command:
> brew install dlib
> 
> and then run pip install again.
> Did it work?

no nothing

**Comment by reliefs** [comment]
try to run 
 brew install cmake

**Comment by Banginpadr** [comment]
> try to run
> brew install cmake

already did too

**Comment by reliefs** [comment]
What if you do pip or pip3 install dlib

**Comment by Banginpadr** [comment]
> What if you do pip or pip3 install dlib

i did it with both, now i installed opencv and it seen like it worked, i ran pip -r install req and now im waiting to see the results. i will let you know how it goes.

**Comment by Banginpadr** [comment]
> What if you do pip or pip3 install dlib

ok it went well...




Requirement already satisfied: Click>=6.0 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from face_recognition->-r requirements.txt (line 2)) (7.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from face_recognition->-r requirements.txt (line 2)) (1.16.2)
Collecting dlib>=19.7 (from face_recognition->-r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz
Installing collected packages: dlib, face-recognition
  Running setup.py install for dlib ... done
Successfully installed dlib-19.17.0 face-recognition-1.2.3
-----------------------------------
i guess that mac users need to install opencv for this to work for some reason

**Comment by reliefs** [comment]
Ok, thanks for the fix I will look more into it. You are the first to test the bot on macOS that I know of, so if you have any problems or feedback, let us know.

**Comment by Banginpadr** [comment]
> Ok, thanks for the fix I will look more into it. You are the first to test the bot on macOS that I know of, so if you have any problems or feedback, let us know.

yes, what ever i do with it i will keep you inform. a quick suggestion, you can install stale( is a github bot to deal with issues). thank you for your work

**Comment by Banginpadr** [comment]
> Ok, thanks for the fix I will look more into it. You are the first to test the bot on macOS that I know of, so if you have any problems or feedback, let us know.

sorry to bother you again. now this is my error


2019-04-07 05:27:02,134 - INFO - Logged-in successfully as 'worldfit'!
2019-04-07 05:27:03,773 - INFO - Stats saved at 2019-04-07 05:27:03.
Searching amandaeliselee for profile pic: 100% 1/1 [00:00<00:00, 1808.67 images/s]
Searching amandaeliselee for posts: 0 media [00:00, ? media/s]
Downloading: 100%|##########| 1/1 [00:00<00:00, 4505.16it/s]
Traceback (most recent call last):
  File "example.py", line 280, in <module>
    instascraper(bot, users, args.amount)
  File "example.py", line 155, in instascraper
    InstaImageScraper()
  File "example.py", line 127, in InstaImageScraper
    imgScraper.scrape()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 666, in scrape
    self.merge_json({ 'GraphImages': self.posts }, '{0}/{1}.json'.format(dst, username))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/instagram_scraper/app.py", line 1155, in merge_json
    key = merged.keys()[0]
TypeError: 'dict_keys' object does not support indexing
2019-04-07 05:27:08,178 - INFO - Bot stopped. Worked: 0:15:42.625570
2019-04-07 05:27:08,178 - INFO - Total requests: 18

**Comment by reliefs** [comment]
I got the same error when i tried to install the script on a clean Ubuntu machine a few days ago, haven't been able to locate the problem, I have reopened the Issue and i will also look further into the problem later today. 

What version of python are you using ? Script has most been tested on python 3.7 =>

**Comment by Banginpadr** [comment]
> I got the same error when i tried to install the script on a clean Ubuntu machine a few days ago, haven't been able to locate the problem, I have reopened the Issue and i will also look further into the problem later today.
> 
> What version of python are you using ? Script has most been tested on python 3.7 =>
> 
> You can try to run:
> 
> python example.py -u yourusername
> 
> But i don't think that will fix the error.

this is the version i have 3.7 just as it say in the logs. im not really good at python. maybe is because in some cases you are using ' instead of " ? sometimes that be a problem because ' is for 2.7 python and " is for version 3

**Comment by reliefs** [comment]
try to change line 

InstaUsername = "siliconeheaven"

To

InstaUsername = "yourusername"

**Comment by Banginpadr** [comment]
> try to change line 29
> 
> InstaUsername = "siliconeheaven"
> 
> To
> 
> InstaUsername = "yourusername"

did that even before running the code

**Comment by Banginpadr** [comment]
> try to change line 29
> 
> InstaUsername = "siliconeheaven"
> 
> To
> 
> InstaUsername = "yourusername"

i will dare to say that you made this program using 2.7 and this is why is not working using 3.7. mixing 2.7 and 3.7 when making a program give these type of problems/bugs/errors

**Comment by reliefs** [comment]
Issue has been located, it's an issue with the instagram-scraper module. 

Issue has been reported here:
https://github.com/rarcega/instagram-scraper/issues/359
