### ISSUE TITLE
invalid syntax

### ISSUE THREAD

**Issue by mehmetze** [instagrambot/Instagram-scraper-with-autopost#7]
Hi,

When run the bot, I get an this error;

  File "example.py", line 169
    #modelcall #modelpose '''
                            ^
SyntaxError: invalid syntax

How to fix it?

**Comment by reliefs** [comment]
do you run it as 
python3 example.py ?

**Comment by mehmetze** [comment]
python2

**Comment by reliefs** [comment]
you need to run is as 
python3 example.py

**Comment by mehmetze** [comment]
And now version Python 3.4.3 but problem is continued.

**Comment by reliefs** [comment]
https://jcutrer.com/linux/upgrade-python37-ubuntu1810

**Comment by mehmetze** [comment]
which version still 3.4.3

**Comment by reliefs** [comment]
the script requires python 3.6+

**Comment by mehmetze** [comment]
Hi,

Traceback (most recent call last):
  File "example.py", line 27, in <module>
    from instabot import Bot, utils
ModuleNotFoundError: No module named 'instabot'


I get an this error message

**Comment by reliefs** [comment]
if you have any module errors install them manually by pip3 or pip3 -r installl requirements.txt, if you have further problems use our docker image.

**Comment by mehmetze** [comment]
Oh finally bots work but when I run the bot after 2-3 minutes I get an error

There is no Face Detected scraping next profile
kimkardashian
image set to private kimkardashian
Traceback (most recent call last):
  File "example.py", line 181, in instascraper
    instascraper(bot, new_media_id, path=POSTED_MEDIAS)
  File "example.py", line 138, in instascraper
    InstaImageScraper()
  File "example.py", line 125, in InstaImageScraper
    imgScraper = insta.InstagramScraper(usernames=[insta_profiles[x]],
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 289, in <module>
    instascraper(bot, users, args.amount)
  File "example.py", line 266, in instascraper
    instascraper(bot, new_media_id, path=POSTED_MEDIAS)
  File "example.py", line 138, in instascraper
    InstaImageScraper()
  File "example.py", line 125, in InstaImageScraper
    imgScraper = insta.InstagramScraper(usernames=[insta_profiles[x]],
IndexError: list index out of range
2019-04-13 23:32:11,267 - INFO - Bot stopped. Worked: 0:11:49.290980
2019-04-13 23:32:11,268 - INFO - Total requests: 9

**Comment by mehmetze** [comment]
How autopost?

**Comment by reliefs** [comment]
are you running docker?

**Comment by mehmetze** [comment]
Yes

**Comment by mehmetze** [comment]
https://prnt.sc/nbm94f

**Comment by reliefs** [comment]
tested with docker works fine.

**Comment by reliefs** [comment]
increase instaprofiles to min 10-20 profiles.

**Comment by mehmetze** [comment]
Again Hi,

Ubuntu I get an continue error when bot start after 5 minutes;

All Posted Medias
[]
Getting media info: 0it [00:00, ?it/s]
Reposting photos: 0it [00:00, ?it/s]
Posting Instagram
image set to private 50cent
Traceback (most recent call last):
  File "example.py", line 260, in instascraper
    os.remove("posted_medias.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'posted_medias.txt'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "example.py", line 289, in <module>
    instascraper(bot, users, args.amount)
  File "example.py", line 266, in instascraper
    instascraper(bot, new_media_id, path=POSTED_MEDIAS)
  File "example.py", line 138, in instascraper
    InstaImageScraper()
  File "example.py", line 125, in InstaImageScraper
    imgScraper = insta.InstagramScraper(usernames=[insta_profiles[x]],
IndexError: list index out of range
2019-04-15 21:41:50,300 - INFO - Bot stopped. Worked: 11:25:43.086724
2019-04-15 21:41:50,300 - INFO - Total requests: 3


So now I setup the docker on ubuntu after "docker build ." command what can I do? How start the bot command? 
(I'm the new of Docker)
Thanks alot

**Comment by reliefs** [comment]
Try to you redownload and make the docker again without changing or saving the instaprofiles.txt

maybe it's a unicode error.

**Comment by reliefs** [comment]
i have just updated the github, try redownload it and run it again.

**Comment by reliefs** [comment]
Also increase min 10-20 profiles inside instaprofiles.txt
